services:
  # Gateway Service
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway
    ports:
      - '8000:8000' # Gateway exposed on port 8080
    depends_on:
      - subscription_service

  # Subscription Service

  subscription_service:
    build:
      context: .
      dockerfile: ./subscription_service/Dockerfile
    container_name: subscription_service
    ports:
      - '8001:8000' # Expose the FastAPI service on port 8001
    depends_on:
      - subscription_db #Ensure the Postgresql starts before the service
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/subscription_db' # Connection string to PostgreSQL
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  subscription_db:
    image: postgres:15
    container_name: subscription_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscription_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
