services:
  # Gateway Service
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - '8000:8000' # Gateway exposed on port 8080
    depends_on:
      - subscription_service

  # Subscription Service

  subscription_service:
    build:
      context: ./subscription_service
      dockerfile: Dockerfile
    container_name: subscription_service
    ports:
      - '8001:8000' # Expose the FastAPI service on port 8001
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/subscription_db' # Connection string to PostgreSQL
    depends_on: 
      - subscription_db

  subscription_db:
    image: postgres:15
    container_name: subscription_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscription_db
    ports:
      - '6432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
